# Generated by Django 5.2.6 on 2025-09-24 12:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='cnpj',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='data_processo',
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_cadastro',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Processo'),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_publicacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Publicação'),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='lote',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='numero_certame',
            field=models.CharField(default='', max_length=50, verbose_name='Número do Certame'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor de Referência'),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='vigencia_meses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Vigência (Meses)'),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='classificacao',
            field=models.CharField(choices=[('Compras', 'Compras'), ('Serviços Comuns', 'Serviços Comuns'), ('Serviços de Engenharia Comuns', 'Serviços de Engenharia Comuns'), ('Obras Comuns', 'Obras Comuns')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Abertura da Contratação'),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='modalidade',
            field=models.CharField(choices=[('Pregão Eletrônico', 'Pregão Eletrônico'), ('Concorrência Eletrônica', 'Concorrência Eletrônica'), ('Dispensa Eletrônica', 'Dispensa Eletrônica'), ('Inexigibilidade Eletrônica', 'Inexigibilidade Eletrônica'), ('Adesão a Registro de Preços', 'Adesão a Registro de Preços'), ('Credenciamento', 'Credenciamento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='numero_processo',
            field=models.CharField(max_length=50, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='api.orgao'),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='situacao',
            field=models.CharField(blank=True, choices=[('Aberto', 'Aberto'), ('Em Pesquisa', 'Em Pesquisa'), ('Aguardando Publicação', 'Aguardando Publicação'), ('Publicado', 'Publicado'), ('Em Contratação', 'Em Contratação'), ('Adjudicado/Homologado', 'Adjudicado/Homologado'), ('Revogado/Cancelado', 'Revogado/Cancelado')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orgao',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='api.municipio'),
        ),
    ]
