# Generated by Django 5.2.6 on 2025-10-22 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lote',
            options={'ordering': ['numero']},
        ),
        migrations.AlterModelOptions(
            name='processolicitatorio',
            options={'ordering': ['-data_processo']},
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='situacao',
        ),
        migrations.AddField(
            model_name='fornecedorprocesso',
            name='fornecedor_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='classificacao',
            field=models.CharField(choices=[('Compras', 'Compras'), ('Serviços Comuns', 'Serviços Comuns'), ('Serviços de Engenharia Comuns', 'Serviços de Engenharia Comuns'), ('Obras Comuns', 'Obras Comuns')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_processo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='entidade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='processos', to='api.entidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='numero_certame',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='numero_processo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='registro_preco',
            field=models.BooleanField(default=False, verbose_name='Registro de Preço'),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='situacao',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Pesquisa', 'Em Pesquisa'), ('Aguardando Publicação', 'Aguardando Publicação'), ('Publicado', 'Publicado'), ('Em Contratação', 'Em Contratação'), ('Adjudicado/Homologado', 'Adjudicado/Homologado'), ('Revogado/Cancelado', 'Revogado/Cancelado')], default='Em Pesquisa', max_length=50),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='tipo_organizacao',
            field=models.CharField(choices=[('Lote', 'Lote'), ('Item', 'Item')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='vigencia_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='modalidade',
            field=models.CharField(choices=[('Pregão Eletrônico', 'Pregão Eletrônico'), ('Concorrência Eletrônica', 'Concorrência Eletrônica'), ('Dispensa Eletrônica', 'Dispensa Eletrônica'), ('Inexigibilidade Eletrônica', 'Inexigibilidade Eletrônica'), ('Adesão a Registro de Preços', 'Adesão a Registro de Preços'), ('Credenciamento', 'Credenciamento')], max_length=50),
        ),
    ]
