# Generated by Django 5.2.6 on 2025-10-22 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lote_options_alter_processolicitatorio_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedorprocesso',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_processo', to='api.processolicitatorio'),
        ),
    ]
