# Generated by Django 5.2.6 on 2025-09-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_municipio_remove_orgao_cnpj_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='item',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='lote',
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='tipo_organizacao',
            field=models.CharField(blank=True, choices=[('Lote', 'Lote'), ('Item', 'Item')], max_length=4, null=True, verbose_name='Tipo de Organização'),
        ),
    ]
