# Generated by Django 5.2.6 on 2025-10-22 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_processolicitatorio_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('ano', models.IntegerField(default=2025, verbose_name='Ano de Exercício')),
            ],
        ),
        migrations.RemoveField(
            model_name='orgao',
            name='municipio',
        ),
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['razao_social']},
        ),
        migrations.AlterModelOptions(
            name='processolicitatorio',
            options={'ordering': ['-data_processo']},
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='data_publicacao',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_criacao_sistema',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='data_processo',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='classificacao',
            field=models.CharField(choices=[('Compras', 'Compras'), ('Serviços Comuns', 'Servicos Comuns'), ('Serviços de Engenharia Comuns', 'Servicos Engenharia'), ('Obras Comuns', 'Obras Comuns')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='data_abertura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='modalidade',
            field=models.CharField(choices=[('Pregão Eletrônico', 'Pregao Eletronico'), ('Concorrência Eletrônica', 'Concorrencia Eletronica'), ('Dispensa Eletrônica', 'Dispensa Eletronica'), ('Inexigibilidade Eletrônica', 'Inexigibilidade Eletronica'), ('Adesão a Registro de Preços', 'Adesao Arp'), ('Credenciamento', 'Credenciamento')], max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='numero_certame',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='numero_processo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='situacao',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Em Pesquisa', 'Em Pesquisa'), ('Aguardando Publicação', 'Aguardando Publicacao'), ('Publicado', 'Publicado'), ('Em Contratação', 'Em Contratacao'), ('Adjudicado/Homologado', 'Adjudicado Homologado'), ('Revogado/Cancelado', 'Revogado Cancelado')], default='Em Pesquisa', max_length=50),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='tipo_organizacao',
            field=models.CharField(choices=[('Lote', 'Lote'), ('Item', 'Item')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='vigencia_meses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together={('razao_social', 'cnpj')},
        ),
        migrations.AddField(
            model_name='orgao',
            name='entidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orgaos', to='api.entidade'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ItemProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('especificacao', models.TextField(blank=True, null=True)),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.processolicitatorio')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('processo', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='ItemFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_cotados', to='api.fornecedor')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_vinculados', to='api.itemprocesso')),
            ],
            options={
                'ordering': ['-criado_em'],
                'unique_together': {('item', 'fornecedor')},
            },
        ),
        migrations.DeleteModel(
            name='Municipio',
        ),
    ]
