# Generated by Django 5.2.6 on 2025-10-22 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_entidade_remove_orgao_municipio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fornecedor',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='itemfornecedor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processolicitatorio',
            options={'ordering': ['-data_abertura']},
        ),
        migrations.RenameField(
            model_name='fornecedor',
            old_name='razao_social',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='processolicitatorio',
            old_name='situacao',
            new_name='status',
        ),
        migrations.AlterUniqueTogether(
            name='fornecedor',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='itemfornecedor',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='itemfornecedor',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='itemfornecedor',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='classificacao',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='data_processo',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='numero_certame',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='numero_processo',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='registro_precos',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='tipo_organizacao',
        ),
        migrations.RemoveField(
            model_name='processolicitatorio',
            name='vigencia_meses',
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemfornecedor',
            name='valor_proposto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemfornecedor',
            name='vencedor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='processolicitatorio',
            name='numero',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='itemfornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.fornecedor'),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='data_abertura',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='modalidade',
            field=models.CharField(choices=[('Pregão Eletrônico', 'Pregao Eletronico'), ('Concorrência Eletrônica', 'Concorrencia Eletronica'), ('Dispensa Eletrônica', 'Dispensa Eletronica'), ('Inexigibilidade Eletrônica', 'Inexigibilidade Eletronica'), ('Adesão a Registro de Preços', 'Adesao Arp'), ('Credenciamento', 'Credenciamento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='processolicitatorio',
            name='valor_referencia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('unidade', models.CharField(max_length=20)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ordem', models.PositiveIntegerField(default=1)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='api.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='api.processolicitatorio')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
        migrations.AlterField(
            model_name='itemfornecedor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propostas', to='api.item'),
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='api.processolicitatorio')),
            ],
            options={
                'unique_together': {('processo', 'numero')},
            },
        ),
        migrations.AddField(
            model_name='item',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens', to='api.lote'),
        ),
        migrations.CreateModel(
            name='FornecedorProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_participacao', models.DateField(auto_now_add=True)),
                ('habilitado', models.BooleanField(default=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='api.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='api.processolicitatorio')),
            ],
            options={
                'unique_together': {('processo', 'fornecedor')},
            },
        ),
        migrations.DeleteModel(
            name='ItemProcesso',
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('processo', 'ordem')},
        ),
    ]
